name: "PlayFab Azure Sync Action"
description: "Sync Azure function to playfab automation after function app deployed."
author: "Bilal-Arvis"
runs: 
  using: node12
  main: index.js
inputs:
  DEVELOPER_SECRET_KEY:
    required: true
    description: "Developer secret key has to be set to upload urls."
  TITLE_ID:
    required: true
    description: "Title id has to be set to find title."