name: "PlayFab Azure Sync Action"
description: "Sync Azure function to playfab automation after function app deployed."
author: "Bilal-Arvis"
runs: 
  using: node16
  main: index.js
inputs:
  developer-secret-key:
    required: true
    description: "Developer secret key has to be set to upload urls."
  title-id:
    required: true
    description: "Title id has to be set to find title."